name: Firstplugin
version: 1.0-SNAPSHOT
main: xyz.bluuuez.firstplugin.Firstplugin
api-version: 1.13
authors: [blu]
description: My first plugin
website: bluuuez.xyz
commands:
  suicide:
    description: kys
  heal:
    description: stop it, get some health